import { Game } from './getGames'

export const mockGetGamesResult: Game[] = [
  {
    id: 1,
    title: 'Overwatch 2',
    thumbnail:
      'https://images.pexels.com/photos/13180751/pexels-photo-13180751.jpeg',
    short_description: 'Hero shooter da Blizzard com batalhas 5v5 dinâmicas.',
    game_url: 'https://www.playoverwatch.com/',
    genre: 'Shooter',
    platform: 'PC/Console',
    publisher: 'Blizzard Entertainment',
    developer: 'Blizzard Entertainment',
    release_date: '2022-10-04',
    freetogame_profile_url: 'https://www.freetogame.com/overwatch-2',
  },
  {
    id: 2,
    title: 'Fortnite',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Fortnite_F_lettermark_logo.png/640px-Fortnite_F_lettermark_logo.png',
    short_description:
      'Battle royale de construção e sobrevivência da Epic Games.',
    game_url: 'https://www.epicgames.com/fortnite',
    genre: 'Battle Royale',
    platform: 'PC/Console/Mobile',
    publisher: 'Epic Games',
    developer: 'Epic Games',
    release_date: '2017-07-21',
    freetogame_profile_url: 'https://www.freetogame.com/fortnite',
  },
  {
    id: 3,
    title: 'League of Legends',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/League_of_Legends_2019_vector.svg/640px-League_of_Legends_2019_vector.svg.png',
    short_description: 'MOBA competitivo 5v5 da Riot Games.',
    game_url: 'https://www.leagueoflegends.com/',
    genre: 'MOBA',
    platform: 'PC',
    publisher: 'Riot Games',
    developer: 'Riot Games',
    release_date: '2009-10-27',
    freetogame_profile_url: 'https://www.freetogame.com/league-of-legends',
  },
  {
    id: 4,
    title: 'Valorant',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Valorant_logo_-_pink_color_version.svg/640px-Valorant_logo_-_pink_color_version.svg.png',
    short_description: 'FPS tático 5v5 focado em habilidade e estratégia.',
    game_url: 'https://playvalorant.com/',
    genre: 'Shooter',
    platform: 'PC',
    publisher: 'Riot Games',
    developer: 'Riot Games',
    release_date: '2020-06-02',
    freetogame_profile_url: 'https://www.freetogame.com/valorant',
  },
  {
    id: 5,
    title: 'Counter-Strike 2',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/en/1/12/Counter-Strike_2_logo.png',
    short_description: 'FPS competitivo e sucessor do lendário CS:GO.',
    game_url: 'https://www.counter-strike.net/',
    genre: 'Shooter',
    platform: 'PC',
    publisher: 'Valve',
    developer: 'Valve',
    release_date: '2023-09-27',
    freetogame_profile_url: 'https://www.freetogame.com/counter-strike-2',
  },
  {
    id: 6,
    title: 'Minecraft',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png',
    short_description: 'Jogo de sobrevivência e construção com blocos.',
    game_url: 'https://www.minecraft.net/',
    genre: 'Sandbox',
    platform: 'PC/Console/Mobile',
    publisher: 'Mojang Studios',
    developer: 'Mojang Studios',
    release_date: '2011-11-18',
    freetogame_profile_url: 'https://www.freetogame.com/minecraft',
  },
  {
    id: 7,
    title: 'Genshin Impact',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/en/d/db/Genshin_Impact_cover.jpg',
    short_description:
      'RPG de ação em mundo aberto com personagens colecionáveis.',
    game_url: 'https://genshin.hoyoverse.com/',
    genre: 'RPG',
    platform: 'PC/Console/Mobile',
    publisher: 'HoYoverse',
    developer: 'HoYoverse',
    release_date: '2020-09-28',
    freetogame_profile_url: 'https://www.freetogame.com/genshin-impact',
  },
  {
    id: 8,
    title: 'Apex Legends',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/en/d/db/Apex_legends_cover.jpg',
    short_description: 'Battle royale em esquadrões com heróis únicos.',
    game_url: 'https://www.ea.com/games/apex-legends',
    genre: 'Battle Royale',
    platform: 'PC/Console',
    publisher: 'Electronic Arts',
    developer: 'Respawn Entertainment',
    release_date: '2019-02-04',
    freetogame_profile_url: 'https://www.freetogame.com/apex-legends',
  },
  {
    id: 9,
    title: 'Dota 2',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Dota_2_logo.jpg',
    short_description: 'MOBA da Valve, sucessor do mod de Warcraft III.',
    game_url: 'https://www.dota2.com/',
    genre: 'MOBA',
    platform: 'PC',
    publisher: 'Valve',
    developer: 'Valve',
    release_date: '2013-07-09',
    freetogame_profile_url: 'https://www.freetogame.com/dota-2',
  },
  {
    id: 10,
    title: 'Call of Duty: Warzone',
    thumbnail:
      'https://upload.wikimedia.org/wikipedia/en/5/52/Call_of_Duty_Warzone_cover.jpg',
    short_description: 'Battle royale gratuito da franquia Call of Duty.',
    game_url: 'https://www.callofduty.com/warzone',
    genre: 'Battle Royale',
    platform: 'PC/Console',
    publisher: 'Activision',
    developer: 'Infinity Ward / Raven Software',
    release_date: '2020-03-10',
    freetogame_profile_url: 'https://www.freetogame.com/cod-warzone',
  },
]
